---
- name: Set install directory
  set_fact:
    install_directory: "{{ homelab_directory }}/homeassistant"

- name: Create a directory for Home Assistant
  file:
    path: "{{ install_directory }}/"
    state: directory

- name: Copy config directory
  copy:
    src: config
    dest: "{{ install_directory }}/"
  become: true

- name: Copy docker-compose.yml file
  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/docker-compose.yaml"

- name: Copy .env file
  copy:
    src: ".env"
    dest: "{{ install_directory }}/.env"

- name: Run docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}"
    state: present # Use 'present' to ensure the services are running
