---
- name: Create a directory for Home Assistant
  file:
    path: "{{ install_directory }}/homeassistant"
    state: directory
- name: Copy the docker-compose.yml file

  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/homeassistant/docker-compose.yaml"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}/homeassistant"
    state: present # Use 'present' to ensure the services are running
