---
- name: Set install directory
  set_fact:
    install_directory: "{{ install_directory }}/telegraf"

- name: Create telegraf directory
  file:
    path: "{{ install_directory }}"
    state: directory

- name: Create volumes directory
  file:
    path: "{{ install_directory }}/volumes"
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/docker-compose.yaml"

- name: Copy telegraf.conf
  copy:
    src: telegraf.conf
    dest: "{{ install_directory }}/volumes/telegraf.conf"

- name: Copy .env file
  copy:
    src: .env
    dest: "{{ install_directory }}/.env"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}"
    state: present # Use 'present' to ensure the services are running
