---
- name: Create a directory for Grafana
  file:
    path: "{{ install_directory }}/grafana"
    state: directory
- name: Copy the docker-compose.yml file
  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/grafana/docker-compose.yaml"
- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}/grafana"
    state: present # Use 'present' to ensure the services are running
