services:
  homepage:
    container_name: homepage
    hostname: homepage
    image: ghcr.io/gethomepage/homepage
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - /etc/pki/ca-trust/source/anchors:/usr/local/share/ca-certificates
    environment:
      HOMEPAGE_VAR_HA_URL:
      HOMEPAGE_VAR_HA_KEY:
      HOMEPAGE_VAR_OCTOPRINT_KEY:
      HOMEPAGE_VAR_PIHOLE_KEY:
      HOMEPAGE_VAR_NPM_USER:
      HOMEPAGE_VAR_NPM_PASSWD:
      HOMEPAGE_VAR_UPTIMEROBOT_KEY:
      HOMEPAGE_VAR_PORTAINER_KEY:
networks:
  default:
    name: scoobydoo
    external: true
