services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    environment:
      GRAFANA_USER:
      GRAFANA_PASSWORD:
    labels:
      - homepage.group=Applications
      - homepage.name=Grafana
      - homepage.icon=grafana
      - homepage.href=https://grafana
      - homepage.widget.type=grafana
      - homepage.widget.url=http://grafana:3000
      - homepage.widget.username=$GRAFANA_USER
      - homepage.widget.password=$GRAFANA_PASSWORD
    volumes:
      - ./volumes/grafana:/var/lib/grafana # after start: sudo chown 472:472 grafana-storage
networks:
  default:
    name: scoobydoo
    external: true
