services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7-alpine
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE:
      DOCKER_INFLUXDB_INIT_USERNAME:
      DOCKER_INFLUXDB_INIT_PASSWORD:
      DOCKER_INFLUXDB_INIT_ORG:
      DOCKER_INFLUXDB_INIT_BUCKET:
    labels:
      - homepage.group=Applications
      - homepage.name=InfluxDB
      - homepage.icon=influxdb
      - homepage.href=https://influxdb
    volumes:
      # Mount for influxdb data directory and configuration
      - ./volumes/influxdbv2:/var/lib/influxdb2

networks:
  default:
    name: scoobydoo
    external: true
