---
- name: Install Home Assistant
  hosts: homelab
  become: true
  vars:
    install_directory: /home/jacopo/homelab/homeassistant
  tasks:
    - name: Create a directory for Home Assistant
      file:
        path: "{{ install_directory }}"
        state: directory
    - name: Copy the docker-compose.yml file

      copy:
        src: docker-compose.yaml
        dest: "{{ install_directory }}/docker-compose.yaml"

    - name: Run Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ install_directory }}"
        state: present # Use 'present' to ensure the services are running
