---
- name: Install Pi-hole
  hosts: homelab
  become: true
  vars:
    install_directory: /home/jacopo/homelab/pihole
  tasks:
    - name: Create a directory for PiHole
      file:
        path: "{{ install_directory }}"
        state: directory

    - name: Copy the docker-compose.yml file
      copy:
        src: docker-compose.yaml
        dest: "{{ install_directory }}/docker-compose.yaml"

    - name: Copy the .env file
      copy:
        src: .env
        dest: "{{ install_directory }}/.env"

    - name: Run Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ install_directory }}"
        state: present # Use 'present' to ensure the services are running
