services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./volumes/etc-pihole:/etc/pihole
      - ./volumes/etc-dnsmasq.d:/etc/dnsmasq.d
    labels:
      - homepage.group=Network
      - homepage.name=PiHole
      - homepage.icon=pi-hole
      - homepage.href=https://pi.hole
      # - homepage.widget.type=pihole
      # - homepage.widget.url=https://pi.hole
      # - homepage.widget.key=$PIHOLE_TOKEN
    cap_add:
      - NET_ADMIN
    environment:
      TZ: Europe/Rome
      WEBPASSWORD:
      WEB_PORT:
      DNSMASQ_USER:
      FTLCONF_LOCAL_IPV4:

  exporter:
    image: jacogasp/pihole-influx-exporter
    container_name: pihole-influx-exporter
    depends_on:
      - pihole
    environment:
      INFLUXDB_URL:
      INFLUXDB_BUCKET:
      PIHOLE_HOST:
      PIHOLE_ENDPOINT:
      PIHOLE_TOKEN:
      POLLING_TIME:

networks:
  default:
    name: scoobydoo
    external: true
