---
- name: Create a directory for Glances
  file:
    path: "{{ install_directory }}/glances"
    state: directory

- name: Copy the docker-compose.yml file
  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/glances/docker-compose.yaml"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}/glances"
    state: present # Use 'present' to ensure the services are running
