services:
  homepage:
    container_name: octoprint
    hostname: octoprint
    image: octoprint/octoprint
    restart: unless-stopped
    volumes:
      - ./config:/octoprint
    env_file: .env
    labels:
      - homepage.group=Home
      - homepage.name=OctoPrint
      - homepage.icon=octoprint
      - homepage.href=$OCTOPRINT_URL
      - homepage.widget.type=octoprint
      - homepage.widget.url=$OCTOPRINT_URL
      - homepage.widget.key=$OCTOPRINT_KEY
    # devices:
    #   - /dev/ttyACM0:/dev/ttyACM0

networks:
  default:
    name: scoobydoo
    external: true
