---
- name: Add iptable-nat module
  community.general.modprobe:
    name: iptable-nat
    state: present

- name: Create a directory for wg-easy
  file:
    path: "{{ install_directory }}/wg-easy"
    state: directory

- name: Copy the docker-compose.yml file
  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/wg-easy/docker-compose.yaml"

- name: Copy the .env file
  copy:
    src: .env
    dest: "{{ install_directory }}/wg-easy.env"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}/wg-easy"
    state: present # Use 'present' to ensure the services are running
