services:
  wg-easy:
    container_name: wg-easy
    hostname: wg-easy
    image: ghcr.io/wg-easy/wg-easy:15
    restart: unless-stopped
    volumes:
      - ./wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    environment:
      USER:
      PASSWD:
    labels:
      - homepage.group=Network
      - homepage.name=Wg-Easy
      - homepage.icon=wireguard
      - homepage.href=https://wg-easy
      # - homepage.widget.type=wgeasy
      # - homepage.widget.version=2
      # - homepage.widget.url=http://wg-easy:51821
      # - homepage.widget.user=$USER
      # - homepage.widget.password=$PASSWD
    ports:
      - 51820:51820/udp
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
networks:
  default:
    name: scoobydoo
    external: true
