services:
  wg-easy:
    container_name: wg-easy
    hostname: wg-easy
    image: weejewel/wg-easy:latest
    restart: unless-stopped
    volumes:
      - ./wireguard:/etc/wireguard
    environment:
      WG_HOST:
      PASSWORD:
      WG_DEVICE:
      WG_DEFAULT_DNS:
      WG_PORT: 51820
      PORT: 51821
      DEBUG: Server,WireGuard
    ports:
      - 51820:51820/udp
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
networks:
  default:
    name: scoobydoo
    external: true
