services:
  esphome:
    container_name: esphome
    hostname: esphome
    image: esphome/esphome
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    # devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      ESPHOME_DASHBOARD_USE_PING: true
      USERNAME:
      PASSWORD:
networks:
  default:
    name: scoobydoo
    external: true
