services:
  esphome:
    container_name: esphome
    hostname: esphome
    image: ghcr.io/esphome/esphome
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    # devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      ESPHOME_DASHBOARD_USE_PING: true
      USERNAME:
      PASSWORD:
    labels:
      - homepage.group=Home
      - homepage.name=ESP Home
      - homepage.icon=esphome
      - homepage.href=https://esphome
      - homepage.widget.type=esphome
      - homepage.widget.url=http://esphome:6052
networks:
  default:
    name: scoobydoo
    external: true
