---
- name: Set install directory
  set_fact:
    install_directory: "{{ homelab_directory }}/nginxproxymanager"

- name: Create Nginx Proxy Manager install directory
  file:
    path: "{{ install_directory }}"
    state: directory

- name: Create volumes directory
  file:
    path: "{{ install_directory }}/volumes"
    state: directory

- name: Create data directory
  file:
    path: "{{ install_directory }}/volumes/data"
    state: directory

- name: Create let's encrypt directory
  file:
    path: "{{ install_directory }}/volumes/letsencrypt"
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/docker-compose.yaml"

- name: Copy .env file
  copy:
    src: ".{{ group_names[0] }}.env"
    dest: "{{ install_directory }}/.env"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}"
    state: present # Use 'present' to ensure the services are running
