---
- name: Install required packages
  dnf:
    name:
      - dnf-utils
      - python3-requests
    state: present
  become: true

- name: Add Docker CE repository
  command: >
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: true

- name: Install Docker
  dnf:
    name: docker-ce
    state: present
    enablerepo: "https://download.docker.com/linux/centos/docker-ce.repo"
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add user to group docker
  user:
    name: jacopo
    groups: docker
    append: yes
  become: true

- name: Create Docker network scoobydoo
  docker_network:
    name: scoobydoo
    state: present
  become: true

- name: Copy the RootCA file to the host
  copy:
    src: "~/Library/Application Support/mkcert/rootCA.pem"
    dest: /etc/pki/ca-trust/source/anchors/homeCA.pem
  become: true
