---
- name: Install required packages
  dnf:
    name:
      - dnf-utils
      - avahi
    state: present
  become: true

- name: Start and enable avahi service
  systemd:
    name: avahi-daemon
    state: started
    enabled: yes
  become: true

- name: Copy avahi-daemon.conf
  copy:
    src: avahi-daemon.conf
    dest: /etc/avahi/avahi-daemon.conf
  become: true
  register: avahiconf

- name: Reload avahi-daemon
  command: avahi-daemon -r
  become: true
  when: avahiconf.changed

- name: Install Docker
  dnf:
    name: docker-ce
    state: present
    enablerepo: "https://download.docker.com/linux/centos/docker-ce.repo"
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create Docker network scoobydoo
  docker_network:
    name: scoobydoo
    state: present

- name: Copy the RootCA file to the host
  copy:
    src: "~/Library/Application Support/mkcert/rootCA.pem"
    dest: /etc/pki/ca-trust/source/anchors/homeCA.pem
