---
- name: Set install directory
  set_fact:
    install_directory: "{{ homelab_directory }}/pihole"

- name: Create pihole install directory
  file:
    path: "{{ install_directory }}"
    state: directory

- name: Create volumes directory
  file:
    path: "{{ install_directory }}/volumes"
    state: directory

- name: Create etc-pihole directory
  file:
    path: "{{ install_directory }}/volumes/etc-pihole"

- name: Create etc-dnsmasq.d directory
  file:
    path: "{{ install_directory }}/volumes/etc-dnsmasq.d"

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/docker-compose.yaml"

- name: Copy the .env file
  copy:
    src: .env
    dest: "{{ install_directory }}/.env"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}"
    state: present # Use 'present' to ensure the services are running
