services:
  telegraf:
    container_name: telegraf
    image: telegraf
    restart: unless-stopped
    user: "${UID}:${GID}"
    volumes:
      - ./volumes/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev:ro
      - /:/hostfs:ro
    environment:
      HOSTNAME:
      INFLUXDB_ENDPOINT:
      INFLUXDB_BUCKET:
      INFLUXDB_ORG:
      INFLUXDB_TOKEN:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc 
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs

networks:
  default:
    name: scoobydoo
    external: true
