---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
- Network:
    - FRITZ!Box:
        href: "https://fritzbox"
        icon: fritzbox
        widget:
          type: fritzbox
          url: http://192.168.178.1
- Cloud:
    - Cloudflare Dashboard:
        href: "https://dash.cloudflare.com"
        description: "Cloudflare Dashboard"
        icon: cloudflare
    - Uptime Robot:
        href: "https://dashboard.uptimerobot.com/monitors"
        description: "Uptime Robot"
        icon: uptime-kuma
        widget:
          type: uptimerobot
          url: "https://api.uptimerobot.com"
          key: {{HOMEPAGE_VAR_UPTIMEROBOT_KEY}}
