---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
- Cloud:
    - Cloudflare Dashboard:
        href: "https://dash.cloudflare.com"
        description: "Cloudflare Dashboard"
        icon: cloudflare
    - Uptime Robot:
        href: "https://dashboard.uptimerobot.com/monitors"
        description: "Uptime Robot"
        icon: uptime-kuma
        widget:
          type: uptimerobot
          url: "https://api.uptimerobot.com"
          key: {{HOMEPAGE_VAR_UPTIMEROBOT_KEY}}
- Monitoring:
    - System Information:
        widget:
          type: glances
          version: 4
          url: http://glances:61208
          metric: info
          chart: false
    - CPU Usage:
        widget:
          type: glances
          version: 4
          url: http://glances:61208
          metric: cpu
          chart: false
    # - Process:
    #     widget:
    #       type: glances
    #       version: 4
    #       url: http://glances:61208
    #       metric: process
    #       chart: false
    - Network Usage:
        widget:
          type: glances
          version: 4
          url: http://glances:61208
          metric: network:eth0
          chart: false
    - Memory Usage:
        widget:
          type: glances
          version: 4
          url: http://glances:61208
          metric: memory
          chart: false
    - CPU Temp Core 0:
        widget:
          type: glances
          version: 4
          url: http://glances:61208
          metric: sensor:Core 0
          chart: false
    - CPU Temp Core 2:
        widget:
          type: glances
          version: 4
          url: http://glances:61208
          metric: sensor:Core 2
          chart: false
