---
- name: Create a directory for Homepage
  file:
    path: "{{ install_directory }}/homepage"
    state: directory

- name: Copy the docker-compose.yml file
  copy:
    src: docker-compose.yaml
    dest: "{{ install_directory }}/homepage/docker-compose.yaml"

- name: Copy config directory
  copy:
    src: config
    dest: "{{ install_directory }}/homepage/"
  become: true

- name: Copy .env file
  copy:
    src: ".env"
    dest: "{{ install_directory }}/homepage/.env"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ install_directory }}/homepage"
    state: present # Use 'present' to ensure the services are running
